replicaCount: 1

image:
  repository: python
  tag: "3.11"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: FLASK_ENV
    value: "production"
  - name: FLASK_PORT
    value: "5000"

serviceAccount:
  create: false
  name: ""
