replicaCount: 1

image:
  repository: nginx
  tag: "alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

serviceAccount:
  create: false
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
livenessProbe:
  tcpSocket:
    port: 80
readinessProbe:
  tcpSocket:
    port: 80
